os: linux
dist: bionic
language: php

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: trusty
    - php: 7.0
      dist: xenial
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
      env:
        - deps=high
        - SYMFONY_PHPUNIT_VERSION=7.5
    - php: nightly
  fast_finish: true
  allow_failures:
    - php: nightly

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install:
  # flags to pass to install
  - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
  # update deps to latest in case of high deps build
  - if [[ "$deps" == "high" ]]; then composer config platform.php 7.2.4; composer update $flags; fi
  # install dependencies using system provided composer binary
  - composer install $flags

script:
  - ./vendor/bin/simple-phpunit

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.4' ]]; then composer require php-coveralls/php-coveralls ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.4' ]]; then php vendor/bin/php-coveralls -v ; fi
