sudo: false

language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: nightly

branches:
  only:
    - master

cache:
  directories:
    - vendor

before_script:
  - mkdir -p build/logs
  - composer update --dev --no-interaction

script:
  - ./vendor/bin/simple-phpunit

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then php vendor/bin/php-coveralls -v ; fi
