name: "Test"

#
# Based on workflows from Composer:
# 
# * https://github.com/composer/composer/blob/2.5.4/.github/workflows/continuous-integration.yml
# * https://github.com/composer/installers/blob/v2.2.0/.github/workflows/continuous-integration.yml
#

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'docs/**'
    tags-ignore:
      - '**'
  pull_request:
    paths-ignore:
      - 'docs/**'
    tags-ignore:
      - '**'

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --prefer-dist"
  COMPOSER_UPDATE_FLAGS: ""

permissions:
  contents: read

jobs:
  tests:
    name: "Test"

    strategy:
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
        composer-version:
          - "v2"
        dependencies:
          - "locked"
        os:
          - "ubuntu-latest"
        experimental:
          - false
        include:
          - php-version: "8.1"
            composer-version: "v2"
            dependencies: "locked"
            os: "windows-latest"
            experimental: false
          - php-version: "8.1"
            composer-version: "v2"
            dependencies: "locked"
            os: "macos-latest"
            experimental: false
          - php-version: "8.1"
            composer-version: "preview"
            dependencies: "locked"
            os: "ubuntu-latest"
            experimental: true
          - php-version: "8.1"
            composer-version: "snapshot"
            dependencies: "locked"
            os: "ubuntu-latest"
            experimental: true
          - php-version: "8.3"
            composer-version: "v2"
            dependencies: "lowest-ignore"
            os: "ubuntu-latest"
            experimental: true
          - php-version: "8.3"
            composer-version: "v2"
            dependencies: "highest-ignore"
            os: "ubuntu-latest"
            experimental: true

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "intl, zip"
          ini-values: "memory_limit=-1, phar.readonly=0, error_reporting=E_ALL, display_errors=On"
          php-version: "${{ matrix.php-version }}"
          tools: "composer:${{ matrix.composer-version }}"

      - name: "Handle lowest dependencies update"
        if: "contains(matrix.dependencies, 'lowest')"
        run: "echo \"COMPOSER_UPDATE_FLAGS=$COMPOSER_UPDATE_FLAGS --prefer-lowest\" >> $GITHUB_ENV"

      - name: "Handle ignore-platform-reqs dependencies update"
        if: "contains(matrix.dependencies, 'ignore')"
        run: "echo \"COMPOSER_FLAGS=$COMPOSER_FLAGS --ignore-platform-req=php\" >> $GITHUB_ENV"

      - name: "Remove platform config to get latest dependencies for current PHP version when build is not locked"
        if: "contains(matrix.dependencies, 'highest') || contains(matrix.dependencies, 'lowest')"
        run: "composer config platform --unset"

      - name: "Allow alpha releases for latest-deps builds to catch problems earlier"
        if: "contains(matrix.dependencies, 'highest')"
        run: "composer config minimum-stability alpha"

      - name: "Update dependencies from composer.json"
        if: "contains(matrix.dependencies, 'highest') || contains(matrix.dependencies, 'lowest')"
        run: "composer update ${{ env.COMPOSER_UPDATE_FLAGS }} ${{ env.COMPOSER_FLAGS }}"

      - name: "Install dependencies from composer.lock"
        if: "matrix.dependencies == 'locked'"
        run: "composer install ${{ env.COMPOSER_FLAGS }}"

      - name: "Prepare git environment"
        run: "git config --global user.name composer && git config --global user.email composer@example.com"

      - name: "Run tests"
        run: "vendor/bin/simple-phpunit --verbose"

  validation:
    name: "Validation"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "intl, zip"
          ini-values: "memory_limit=-1, phar.readonly=0, error_reporting=E_ALL, display_errors=On"
          php-version: "7.4"
          tools: composer

      - name: "Install dependencies from composer.lock"
        run: "composer install ${{ env.COMPOSER_FLAGS }}"

      - name: "Validate composer.json"
        run: "composer validate --strict"
